### ISSUE TITLE
dont show stash version downloaded, and left two data archives..

### ISSUE THREAD

**Issue by clockterra** [lunalik2/Unofficial-ReiNX-SD-Stash-Updater#2]
it needs to show the Stash version downloaded.

it left two data archives after the work, that could be automaticaly deleted..

**Comment by lunalik2** [comment]
Added data archive issue fix in https://github.com/lunalik2/Unofficial-ReiNX-SD-Stash-Updater/commit/d64c21c6f59a096cc0462eca27da2ea30c930083. Other issue already has a page.
