### ISSUE TITLE
improving the gui side with lights 

### ISSUE THREAD

**Issue by clockterra** [lunalik2/Unofficial-ReiNX-SD-Stash-Updater#4]
can you put two lights down the download, one red and one green, and green its activated as soon you downloaded the stash..
red one is activated until you push download that then lights off..
or left it as you have and only take out the new ok window that is not well looking..
you push download main window disapear to show script running and when finish comeback the main window with a green light next to download button

**Comment by lunalik2** [comment]
https://github.com/lunalik2/Unofficial-ReiNX-SD-Stash-Updater/commit/b71c69e996f442a61f55542d06264b216e31045c Eh, close enough.
